services:
  db:
    image: postgres:17.2
    comtainern_name: postgresdb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: postgres
    # volumes:
    # - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  dbadmin:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
